version: "3.8"
services:
  backend:
    restart: always
    build: src
    depends_on:
      - database
    networks:
      - backend-database
    ports:
      - 127.0.0.1:80:80
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: musixdb
      DB_USERNAME: musix
      DB_PASSWORD: 12345
      LOG_CHANNEL: stdout

  database:
    restart: always
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend-database
    environment:
      MYSQL_DATABASE: musixdb
      MYSQL_USER: musix
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
networks:
  backend-database: